/* Tiếng Trung HSK1 trong Mimi: Bước 0 (thanh điệu, phụ âm, vần, chữ Hán) + 15 bài + luyện tập. Dữ liệu: hsk1-data.js */
(()=>{
const H=(window.HSK1||{}).lessons;if(!H)return;
const $=id=>document.getElementById(id),LS=localStorage,toast=m=>{try{showToast(m)}catch(e){alert(m)}};
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),shuf=a=>[...a].sort(()=>Math.random()-.5);
let P={};try{P=JSON.parse(LS.getItem('PE_ZH')||'{}')}catch(e){}const save=()=>{try{LS.setItem('PE_ZH',JSON.stringify(P))}catch(e){}};
const xp=k=>{try{window.ent303AwardXP&&window.ent303AwardXP(k)}catch(e){}};
const EM=['👋','🙏','🪪','👩‍🏫','🔢','🍜','📅','🍵','🏥','🪑','⏰','🌦️','📞','👗','✈️'],ALL=H.flatMap(l=>l.w);
const T=['āēīōūǖ','áéíóúǘ','ǎěǐǒǔǚ','àèìòùǜ'],py=s=>esc(s).replace(/[āēīōūǖáéíóúǘǎěǐǒǔǚàèìòùǜ]/g,c=>`<b class="zt${T.findIndex(t=>t.includes(c))+1}">${c}</b>`);
let V=[],warned=0;const lv=()=>{try{V=speechSynthesis.getVoices()||[]}catch(e){}};lv();try{speechSynthesis.addEventListener('voiceschanged',lv)}catch(e){}
function say(t){if(!window.speechSynthesis)return toast('Trình duyệt chưa hỗ trợ đọc');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='zh-CN';const f=V.filter(v=>/^zh/i.test(v.lang)),v=f.find(x=>x.voiceURI===LS.getItem('PE_ZHV'))||f.find(x=>/zh[-_]CN/i.test(x.lang))||f[0];if(v)u.voice=v;else if(!warned){warned=1;toast('Máy chưa có giọng tiếng Trung. Hãy tải trong Cài đặt → Văn bản sang giọng nói.')}u.rate=.8;speechSynthesis.speak(u)}
window.ZH={say:b=>say(b.dataset.t)};
document.head.insertAdjacentHTML('beforeend',`<style>#zh-section{padding-bottom:20px}.zc{border:1px solid var(--acc-b,#ffe4e6);border-radius:24px;padding:16px;margin:12px 0;background:rgba(255,255,255,.94)}body[data-mode=dark] .zc{background:#1e2040;border-color:#33365f;color:#e5e7eb}
.zb{padding:10px 14px;border-radius:14px;background:#fff1f2;color:#e11d48;font-weight:800;font-size:13px;min-height:44px}.zb.on,.zb.pri{background:linear-gradient(135deg,var(--acc,#f43f5e),var(--acc2,#fb923c));color:#fff}
.zg{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:10px}.zt1{color:#ef4444}.zt2{color:#16a34a}.zt3{color:#2563eb}.zt4{color:#9333ea}
.zbig{font-size:3.6rem;line-height:1.2}.zpg{height:6px;background:#8883;border-radius:9px;overflow:hidden;margin-top:6px}.zpg i{display:block;height:100%;background:#22c55e}.zm{color:#8b8190;font-size:12px}
.zr{display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid #8882}.zr:last-child{border:0}.zr .h{font-size:1.6rem;min-width:3.6rem}.zg1{flex:1}.zd{opacity:.55}
.zo{display:block;width:100%;margin:8px 0;text-align:left;padding:12px;border-radius:14px;background:#fff1f2;font-weight:700;color:#334155}body[data-mode=dark] .zo{background:#2a2d55;color:#e5e7eb}.zo.good{background:#16a34a!important;color:#fff}.zo.bad{background:#dc2626!important;color:#fff}.zrow{display:flex;gap:8px;flex-wrap:wrap}.zrow>*{flex:1}</style>`);
const sec=document.createElement('div');sec.id='zh-section';sec.className='hidden';($('content-area')||document.body).appendChild(sec);
let Z={v:'home'},Q=null;
const go=z=>{if(z.v==='quiz')Q=null;history.pushState({s:'zh',z},'');Z=z;draw()};
const prog=ws=>{const n=ws.filter(w=>P[w[0]]).length;return`<div class="zpg"><i style="width:${ws.length?n/ws.length*100:0}%"></i></div><div class="zm">${n}/${ws.length} đã thuộc</div>`};
const sb=t=>`<button class="zb" data-t="${esc(t)}" onclick="ZH.say(this)" aria-label="Nghe">🔊</button>`;
/* ---- Bước 0: nội dung nhập môn ---- */
const TONES=[['妈','mā','mẹ','Cao và đều, như giữ một nốt cao kéo dài.'],['麻','má','tê, gai','Đi lên, như hỏi lại “hả?”.'],['马','mǎ','ngựa','Xuống thấp rồi nhích lên nhẹ.'],['骂','mà','mắng','Rơi dứt khoát từ cao xuống thấp, như ra lệnh “đi!”.'],['吗','ma','trợ từ hỏi','Nhẹ và ngắn, không nhấn.']];
const INI=[['b','不','bù','giống “p” trong “pa”, không bật hơi'],['p','朋','péng','như b nhưng bật hơi mạnh (thổi tờ giấy sẽ bay)'],['m','妈','mā','như “m”'],['f','飞','fēi','như “ph”'],['d','大','dà','giống “t”, không bật hơi'],['t','他','tā','như d nhưng bật hơi'],['n','你','nǐ','như “n”'],['l','老','lǎo','như “l”'],['g','个','gè','giống “c/k”, không bật hơi'],['k','看','kàn','như g nhưng bật hơi'],['h','好','hǎo','như “kh/h”, hơi thở từ cổ họng'],['j','家','jiā','giống “ch” nhẹ, lưỡi bẹt, không bật hơi'],['q','七','qī','như j nhưng bật hơi'],['x','谢','xiè','giống “x” nhẹ, miệng bẹt'],['zh','这','zhè','giống “tr”, uốn lưỡi, không bật hơi'],['ch','吃','chī','như zh nhưng bật hơi'],['sh','是','shì','giống “s” uốn lưỡi'],['r','热','rè','giống “r” uốn lưỡi, hơi rung'],['z','在','zài','giống “ch/ts”, lưỡi thẳng, không bật hơi'],['c','菜','cài','như z nhưng bật hơi'],['s','四','sì','giống “x/s”, lưỡi thẳng']];
const FIN=[['a','八','bā'],['o','我','wǒ'],['e','喝','hē'],['i','你','nǐ'],['u','五','wǔ'],['ü','女','nǚ'],['ai','爱','ài'],['ei','谁','shéi'],['ao','好','hǎo'],['ou','都','dōu'],['an','看','kàn'],['en','很','hěn'],['ang','上','shàng'],['eng','朋','péng'],['ong','中','zhōng'],['ia','家','jiā'],['ie','谢','xiè'],['iao','小','xiǎo'],['iu','六','liù'],['ian','年','nián'],['in','今','jīn'],['ing','请','qǐng'],['uo','说','shuō'],['ui','岁','suì'],['üe','月','yuè']];
const cell=(a,c,p,n)=>`<div class="zc" style="margin:0;text-align:center"><div class="zbig" style="font-size:1.8rem;font-weight:900">${esc(a)}</div><div style="font-size:1.6rem">${c}</div><div>${py(p)}</div>${n?`<div class="zm">${n}</div>`:''}${sb(c)}</div>`;
function intro(t){const tabs=[['t','Thanh điệu'],['i','Phụ âm'],['f','Vần'],['h','Chữ Hán']],h=`<div class="zrow">${tabs.map(x=>`<button class="zb ${t===x[0]?'on':''}" onclick="Z_.tab('${x[0]}')">${x[1]}</button>`).join('')}</div>`;
 if(t==='t')return h+`<div class="zc"><b>Tiếng Trung có 4 thanh + thanh nhẹ.</b> Cùng âm “ma” nhưng đổi thanh là đổi nghĩa. Bấm 🔊 và nhại theo.</div>`+TONES.map((x,i)=>`<div class="zc"><div class="zr"><span class="h">${x[0]}</span><div class="zg1"><div>${py(x[1])} <span class="zm">· ${x[2]}</span></div><div class="zm">Thanh ${i<4?i+1:'nhẹ'}: ${x[3]}</div></div>${sb(x[0])}</div></div>`).join('')+`<div class="zc"><b>3 quy tắc đổi thanh cần nhớ</b><p>• Hai thanh 3 đứng cạnh nhau: chữ đầu đọc thành thanh 2. 你好 viết nǐ hǎo nhưng đọc “ní hǎo”.</p><p>• 不 (bù) đứng trước thanh 4 thì đọc bú: 不是 bú shì.</p><p>• 一 (yī) đứng trước thanh 4 thì đọc yí (一个 yí gè); trước thanh 1, 2, 3 thì đọc yì (一天 yì tiān).</p></div>`;
 if(t==='i')return h+`<div class="zc"><b>21 phụ âm.</b> Mô tả “giống âm tiếng Việt” chỉ là gần đúng. Hãy nghe 🔊 để chỉnh. Điểm khó nhất: <b>bật hơi</b> (p, t, k, q, ch, c) và <b>uốn lưỡi</b> (zh, ch, sh, r).</div><div class="zg">${INI.map(x=>cell(x[0],x[1],x[2],x[3])).join('')}</div>`;
 if(t==='f')return h+`<div class="zc"><b>Vần (phần sau phụ âm).</b> Chữ ü đọc như “uy” kéo tròn môi (女 nǚ). Sau j, q, x, y thì viết u nhưng vẫn đọc ü (月 yuè).</div><div class="zg">${FIN.map(x=>cell(x[0],x[1],x[2])).join('')}</div>`;
 return h+`<div class="zc"><b>Chữ Hán không đọc theo mặt chữ.</b> Mỗi chữ là một âm tiết, và pinyin là “cách đọc” của chữ. Mẹo: học chữ cùng <b>Hán Việt</b> (老师 = lão sư), vì rất nhiều từ tiếng Việt gốc Hán.</p><p><b>Bộ thủ thường gặp:</b> 氵nước · 亻người · 口 miệng · 女 nữ · 心 tâm · 日 mặt trời · 木 cây · 讠lời nói.</p><p><b>Quy tắc viết nét:</b> trái trước phải sau · trên trước dưới sau · ngang trước sổ sau · phẩy trước mác sau · ngoài trước trong sau · khung kín thì đóng đáy sau cùng.</div>`}
window.Z_={tab:t=>{Z.t=t;history.replaceState({s:'zh',z:Z},'');draw()},m:m=>{Z.m=m;Z.k=0;Z.f=0;history.replaceState({s:'zh',z:Z},'');draw()}};
/* ---- Màn hình ---- */
function draw(){const a=sec,z=Z;window.scrollTo(0,0);
 if(z.v==='home'){const n=ALL.filter(w=>P[w[0]]).length,f=V.filter(v=>/^zh/i.test(v.lang));
  a.innerHTML=`<div class="zc" style="background:linear-gradient(135deg,var(--acc,#f43f5e),var(--acc2,#fb923c));color:#fff"><h2 class="text-xl font-black">🇨🇳 Tiếng Trung HSK1</h2><p style="opacity:.9">Học từ con số 0: phát âm trước, rồi 15 bài. ${n}/${ALL.length} từ đã thuộc.</p><div class="zpg"><i style="width:${n/ALL.length*100}%"></i></div></div>
  <button class="zc" style="width:100%;text-align:left" onclick="Z_.go({v:'intro',t:'t'})"><span style="font-size:2rem">🌱</span> <b>Bước 0 · Làm quen: thanh điệu, phụ âm, vần, chữ Hán</b><div class="zm">Bắt đầu ở đây nếu bạn chưa biết gì</div></button>
  <div class="zg">${H.map((l,i)=>`<button class="zc" style="margin:0;text-align:left" onclick="Z_.go({v:'lesson',i:${i},m:'c',k:0})"><span style="font-size:1.8rem">${EM[i]}</span><b style="display:block">Bài ${l.n}</b><div class="zm">${esc(l.vi)}</div>${prog(l.w)}</button>`).join('')}</div>
  <div class="zrow"><button class="zb pri" onclick="Z_.go({v:'quiz',i:-1})">🎲 Ôn tổng hợp (10 câu)</button></div>
  <div class="zc"><b>🔊 Giọng đọc tiếng Trung</b> ${f.length?`<select onchange="localStorage.setItem('PE_ZHV',this.value)" style="max-width:100%;padding:6px;border-radius:10px">${f.map(v=>`<option value="${esc(v.voiceURI)}" ${LS.getItem('PE_ZHV')===v.voiceURI?'selected':''}>${esc(v.name)} (${esc(v.lang)})</option>`).join('')}</select>`:'<span class="zm">Máy chưa có giọng tiếng Trung</span>'} ${sb('你好')}</div>`}
 if(z.v==='intro')a.innerHTML=intro(z.t);
 if(z.v==='lesson'){const l=H[z.i],w=l.w[z.k||0],seg=`<div class="zrow"><button class="zb ${z.m==='c'?'on':''}" onclick="Z_.m('c')">🃏 Thẻ</button><button class="zb ${z.m==='l'?'on':''}" onclick="Z_.m('l')">📋 Danh sách</button></div>`,pq=`<button class="zb pri" style="width:100%;margin-top:10px" onclick="Z_.go({v:'quiz',i:${z.i}})">✍️ Luyện tập bài ${l.n}</button>`;
  a.innerHTML=`<div class="zc"><b>${EM[z.i]} Bài ${l.n}: ${esc(l.t)}</b><div class="zm">${esc(l.vi)}</div>${prog(l.w)}</div>`+seg+(z.m==='c'?`<div class="zc" style="text-align:center;min-height:240px;cursor:pointer;display:flex;flex-direction:column;justify-content:center;align-items:center" onclick="Z_.flip()"><div class="zm">${z.k+1}/${l.w.length} · chạm để lật</div><div class="zbig">${esc(w[0])}</div>${z.f?`<div style="font-size:1.4rem">${py(w[1])}</div><div>${esc(w[2])}</div>${w[3]?`<div class="zm">Hán Việt: ${esc(w[3])}</div>`:''}`:''}</div><div class="zrow">${sb(w[0])}<button class="zb ${P[w[0]]?'pri':''}" onclick="Z_.tg(${z.k})">${P[w[0]]?'✅ Đã thuộc':'⬜ Đánh dấu thuộc'}</button></div><div class="zrow" style="margin-top:8px"><button class="zb" onclick="Z_.nx(-1)">← Trước</button><button class="zb" onclick="Z_.nx(1)">Sau →</button></div>`:`<div class="zc">${l.w.map((x,k)=>`<div class="zr ${P[x[0]]?'zd':''}"><span class="h">${esc(x[0])}</span><div class="zg1"><div>${py(x[1])}</div><div>${esc(x[2])}${x[3]?` <span class="zm">· ${esc(x[3])}</span>`:''}</div></div>${sb(x[0])}<button class="zb" onclick="Z_.tg(${k})">${P[x[0]]?'✅':'⬜'}</button></div>`).join('')}</div>`)+pq}
 if(z.v==='quiz')qz()}
Object.assign(window.Z_,{go,flip:()=>{Z.f=!Z.f;draw()},nx:d=>{const n=H[Z.i].w.length;Z.k=(Z.k+d+n)%n;Z.f=0;draw()},tg:k=>{const w=H[Z.i].w[k];P[w[0]]=!P[w[0]];if(P[w[0]])xp('vocab_learned');save();draw()}});
/* ---- Luyện tập: 4 dạng, đáp án nhiễu lấy cùng bài, xáo mỗi lần ---- */
function mk(i){const pool=i<0?ALL:H[i].w,types=['m','w','l','r'];return{n:0,sc:0,bad:[],q:shuf(pool).slice(0,10).map((w,n)=>{const ty=types[n%4],f=ty==='m'?2:ty==='r'?1:0,seen=new Set([w[f]]),o=[w];for(const x of shuf([...pool,...ALL])){if(o.length>=4)break;if(!seen.has(x[f])){seen.add(x[f]);o.push(x)}}return{w,ty,f,o:shuf(o)}})}}
function qz(){const a=sec,i=Z.i;if(!Q)Q=mk(i);
 if(Q.n>=Q.q.length){const p=Q.sc/Q.q.length;if(!Q.done){Q.done=1;if(p>=1)xp('quiz_complete_100');else if(p>=.8)xp('quiz_complete_80')}a.innerHTML=`<div class="zc" style="text-align:center"><div style="font-size:3rem">${p>=.8?'🏆':p>=.5?'👍':'💪'}</div><h3 class="text-xl font-black">${Q.sc}/${Q.q.length} câu đúng</h3>${Q.bad.length?`<p class="zm">Cần ôn lại:</p>${Q.bad.map(w=>`<div>${esc(w[0])} · ${py(w[1])} · ${esc(w[2])}</div>`).join('')}`:'<p>Không sai câu nào!</p>'}<div class="zrow" style="margin-top:12px"><button class="zb pri" onclick="Z_.again()">Làm lại</button><button class="zb" onclick="history.back()">Quay lại</button></div></div>`;return}
 const c=Q.q[Q.n],w=c.w,ask=c.ty==='l'?`${sb(w[0]).replace('🔊','🔊 Nghe')}<p class="zm">Chọn chữ đúng</p>`:c.ty==='w'?`<div style="font-size:1.5rem">${esc(w[2])}</div><p class="zm">Chọn chữ đúng</p>`:`<div style="font-size:3rem">${esc(w[0])}</div>${sb(w[0])}<p class="zm">${c.ty==='m'?'Nghĩa là gì?':'Cách đọc đúng?'}</p>`;
 a.innerHTML=`<div class="zc"><div class="zm">Câu ${Q.n+1}/${Q.q.length}</div><div class="zpg"><i style="width:${Q.n/Q.q.length*100}%"></i></div><div style="text-align:center;margin:12px 0">${ask}</div>${c.o.map(x=>`<button class="zo" data-k="${x===w?1:0}" style="${c.f===0?'font-size:1.6rem':''}">${c.f===1?py(x[1]):esc(x[c.f])}</button>`).join('')}<div id="zfb"></div></div>`;
 if(c.ty==='l')setTimeout(()=>say(w[0]),250);
 a.querySelectorAll('.zo').forEach(b=>b.onclick=()=>{const ok=b.dataset.k==='1';a.querySelectorAll('.zo').forEach(x=>{x.disabled=true;if(x.dataset.k==='1')x.classList.add('good')});if(ok){Q.sc++;xp('vocab_correct');try{correctFx()}catch(e){}}else{b.classList.add('bad');Q.bad.push(w);try{wrongFx()}catch(e){}}
  $('zfb').innerHTML=`<div class="zm" style="margin-top:8px">${ok?'✅ Chính xác!':'❌ Chưa đúng.'} <b>${esc(w[0])}</b> · ${py(w[1])} · ${esc(w[2])}</div><button class="zb pri" style="width:100%;margin-top:8px" onclick="Z_.next()">Tiếp →</button>`;if(c.ty!=='l')say(w[0])})}
Object.assign(window.Z_,{next:()=>{Q.n++;draw()},again:()=>{Q=mk(Z.i);draw()}});
/* ---- Gắn vào điều hướng của app (Back, nút Back điện thoại, lịch sử) ---- */
const prev=window.switchSection;
window.switchSection=function(s){prev.apply(this,arguments);if(s==='zh'){const st=history.state;Z=(st&&st.s==='zh'&&st.z)||{v:'home'};if(Z.v!=='quiz')Q=null;sec.classList.remove('hidden');$('unit-hero')?.classList.add('hidden');draw()}else sec.classList.add('hidden')};
/* Mimi: Tiếng Trung là môn ngang hàng, mở từ màn chọn môn (không còn là nút phụ trong trang chủ English). */
})();
