/* HSK1 — từ vựng theo 15 bài của giáo trình "HSK Standard Course 1" (chỉ lấy: từ, pinyin, nghĩa).
   Nghĩa tiếng Việt và âm Hán Việt (hv) do AI soạn: cần rà lại trước khi gửi lớp.
   Mỗi từ: [chữ Hán, pinyin, nghĩa Việt, Hán Việt (có thể để rỗng)] */
window.HSK1={lessons:[
{n:1,t:"你好",vi:"Xin chào",w:[["你","nǐ","bạn","nhĩ"],["好","hǎo","tốt, khỏe","hảo"],["对不起","duìbuqǐ","xin lỗi","đối bất khởi"],["没关系","méi guānxi","không sao đâu","một quan hệ"]]},
{n:2,t:"谢谢你",vi:"Cảm ơn bạn",w:[["不","bù","không","bất"],["不客气","bú kèqi","đừng khách sáo","bất khách khí"],["谢谢","xièxie","cảm ơn","tạ"],["再见","zàijiàn","tạm biệt","tái kiến"]]},
{n:3,t:"你叫什么名字",vi:"Bạn tên là gì",w:[["叫","jiào","gọi, tên là","khiếu"],["什么","shénme","cái gì",""],["名字","míngzi","tên","danh tự"],["我","wǒ","tôi",""],["是","shì","là","thị"],["老师","lǎoshī","giáo viên","lão sư"],["学生","xuésheng","học sinh","học sinh"],["人","rén","người","nhân"],["吗","ma","trợ từ nghi vấn (…không?)",""],["中国","Zhōngguó","Trung Quốc","Trung Quốc"],["美国","Měiguó","nước Mỹ","Mỹ quốc"]]},
{n:4,t:"她是我的汉语老师",vi:"Cô ấy là giáo viên tiếng Trung của tôi",w:[["她","tā","cô ấy",""],["他","tā","anh ấy",""],["谁","shéi","ai",""],["的","de","của",""],["汉语","Hànyǔ","tiếng Hán","Hán ngữ"],["哪","nǎ","nào",""],["同学","tóngxué","bạn học","đồng học"],["朋友","péngyou","bạn bè","bằng hữu"],["呢","ne","thế còn…? (trợ từ)",""]]},
{n:5,t:"她女儿今年二十岁",vi:"Con gái cô ấy năm nay hai mươi tuổi",w:[["一","yī","một","nhất"],["二","èr","hai","nhị"],["三","sān","ba","tam"],["四","sì","bốn","tứ"],["五","wǔ","năm","ngũ"],["六","liù","sáu","lục"],["七","qī","bảy","thất"],["八","bā","tám","bát"],["九","jiǔ","chín","cửu"],["十","shí","mười","thập"],["多","duō","nhiều; bao nhiêu (hỏi mức độ)","đa"],["大","dà","lớn; (tuổi) lớn","đại"],["几","jǐ","mấy","kỷ"],["岁","suì","tuổi","tuế"],["了","le","rồi (trợ từ)",""],["有","yǒu","có","hữu"],["家","jiā","nhà, gia đình","gia"],["女儿","nǚ'ér","con gái","nữ nhi"]]},
{n:6,t:"我会说汉语",vi:"Tôi biết nói tiếng Trung",w:[["会","huì","biết, có thể (học được)","hội"],["说","shuō","nói","thuyết"],["菜","cài","món ăn, rau","thái"],["妈妈","māma","mẹ",""],["很","hěn","rất","ngận"],["读","dú","đọc","độc"],["写","xiě","viết","tả"],["字","zì","chữ","tự"],["做","zuò","làm","tố"],["怎么","zěnme","thế nào, sao","chẩm ma"]]},
{n:7,t:"今天几号",vi:"Hôm nay ngày mấy",w:[["号","hào","ngày (trong tháng)","hiệu"],["月","yuè","tháng","nguyệt"],["星期","xīngqī","tuần, thứ","tinh kỳ"],["今天","jīntiān","hôm nay","kim thiên"],["明天","míngtiān","ngày mai","minh thiên"],["昨天","zuótiān","hôm qua","tạc thiên"],["去","qù","đi","khứ"],["学校","xuéxiào","trường học","học hiệu"],["看","kàn","xem, nhìn, đọc","khán"],["书","shū","sách","thư"],["请","qǐng","xin mời, làm ơn","thỉnh"]]},
{n:8,t:"我想喝茶",vi:"Tôi muốn uống trà",w:[["想","xiǎng","muốn, nhớ","tưởng"],["喝","hē","uống","hát"],["茶","chá","trà","trà"],["吃","chī","ăn","ngật"],["米饭","mǐfàn","cơm","mễ phạn"],["下午","xiàwǔ","buổi chiều","hạ ngọ"],["商店","shāngdiàn","cửa hàng","thương điếm"],["买","mǎi","mua","mãi"],["个","gè","cái (lượng từ chung)","cá"],["杯子","bēizi","cái cốc","bôi tử"],["这","zhè","này","giá"],["那","nà","kia","na"],["多少","duōshao","bao nhiêu","đa thiểu"],["钱","qián","tiền","tiền"],["块","kuài","đồng (đơn vị tiền)","khối"]]},
{n:9,t:"你儿子在哪儿工作",vi:"Con trai bạn làm việc ở đâu",w:[["在","zài","ở, tại","tại"],["哪儿","nǎr","ở đâu",""],["工作","gōngzuò","làm việc; công việc","công tác"],["儿子","érzi","con trai","nhi tử"],["医生","yīshēng","bác sĩ","y sinh"],["医院","yīyuàn","bệnh viện","y viện"],["爸爸","bàba","bố",""],["小","xiǎo","nhỏ","tiểu"],["猫","māo","mèo","miêu"],["狗","gǒu","chó","cẩu"],["椅子","yǐzi","cái ghế","y tử"],["下","xià","dưới, xuống","hạ"]]},
{n:10,t:"我能坐这儿吗",vi:"Tôi ngồi đây được không",w:[["坐","zuò","ngồi","tọa"],["能","néng","có thể, được phép","năng"],["桌子","zhuōzi","cái bàn","trác tử"],["电脑","diànnǎo","máy tính","điện não"],["和","hé","và","hòa"],["本","běn","quyển (lượng từ sách)","bản"],["里","lǐ","trong, bên trong","lý"],["前面","qiánmiàn","phía trước","tiền diện"],["后面","hòumiàn","phía sau","hậu diện"],["没有","méiyǒu","không có","một hữu"],["上","shang","trên","thượng"]]},
{n:11,t:"现在几点",vi:"Bây giờ mấy giờ",w:[["点","diǎn","giờ (chỉ giờ)","điểm"],["现在","xiànzài","bây giờ","hiện tại"],["时候","shíhou","lúc, khi","thời hậu"],["中午","zhōngwǔ","buổi trưa","trung ngọ"],["电影","diànyǐng","phim","điện ảnh"],["我们","wǒmen","chúng tôi, chúng ta",""],["回","huí","về, quay lại","hồi"],["住","zhù","ở, sống tại","trú"],["北京","Běijīng","Bắc Kinh","Bắc Kinh"]]},
{n:12,t:"明天天气怎么样",vi:"Ngày mai thời tiết thế nào",w:[["天气","tiānqì","thời tiết","thiên khí"],["怎么样","zěnmeyàng","thế nào","chẩm ma dạng"],["太","tài","quá","thái"],["热","rè","nóng","nhiệt"],["冷","lěng","lạnh","lãnh"],["下雨","xià yǔ","trời mưa","hạ vũ"],["小姐","xiǎojiě","cô, tiểu thư","tiểu thư"],["来","lái","đến","lai"],["水","shuǐ","nước","thủy"],["水果","shuǐguǒ","hoa quả","thủy quả"],["爱","ài","yêu, thích","ái"],["些","xiē","một vài, những","ta"]]},
{n:13,t:"他在学做中国菜呢",vi:"Anh ấy đang học nấu món Trung Quốc",w:[["喂","wèi","a lô","uy"],["打电话","dǎ diànhuà","gọi điện thoại","đả điện thoại"],["电视","diànshì","tivi","điện thị"],["喜欢","xǐhuan","thích","hỉ hoan"],["睡觉","shuìjiào","ngủ","thụy giác"],["上午","shàngwǔ","buổi sáng","thượng ngọ"],["学习","xuéxí","học, học tập","học tập"]]},
{n:14,t:"她买了不少衣服",vi:"Cô ấy mua khá nhiều quần áo",w:[["东西","dōngxi","đồ, đồ vật","đông tây"],["都","dōu","đều","đô"],["分钟","fēnzhōng","phút","phân chung"],["开","kāi","lái (xe); mở","khai"],["看见","kànjiàn","nhìn thấy","khán kiến"],["漂亮","piàoliang","xinh, đẹp","phiêu lượng"],["苹果","píngguǒ","quả táo","bình quả"],["少","shǎo","ít","thiểu"],["先生","xiānsheng","ông, ngài; chồng","tiên sinh"],["衣服","yīfu","quần áo","y phục"],["一点儿","yìdiǎnr","một chút","nhất điểm nhi"]]},
{n:15,t:"我是坐飞机来的",vi:"Tôi đến bằng máy bay",w:[["出租车","chūzūchē","taxi","xuất tô xa"],["饭店","fàndiàn","khách sạn, nhà hàng","phạn điếm"],["飞机","fēijī","máy bay","phi cơ"],["高兴","gāoxìng","vui, mừng","cao hứng"],["年","nián","năm","niên"],["认识","rènshi","quen, biết (người)","nhận thức"],["听","tīng","nghe","thính"]]}
]};
