/* 日本語 N5 trong Mimi: Từ vựng • Flashcard • Chữ cái (bảng kana) • Quiz. Tiến độ dùng chung khóa PE_LANG ("ja:"+từ) với trang luyện cũ. */
(()=>{
const $=id=>document.getElementById(id),LS=localStorage,esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const toast=m=>{try{showToast(m)}catch(e){alert(m)}},xp=(k,r)=>{try{window.ent303AwardXP&&window.ent303AwardXP(k,r)}catch(e){}};
const shuf=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const LV=[{"id":"Bảng chữ cái","topics":[{"t":"Hiragana hàng A","e":"あ","w":[["あ","a","a"],["い","i","i"],["う","u","u"],["え","e","e"],["お","o","o"]]},{"t":"Hiragana hàng K","e":"か","w":[["か","ka","ka"],["き","ki","ki"],["く","ku","ku"],["け","ke","ke"],["こ","ko","ko"]]},{"t":"Hiragana hàng S","e":"さ","w":[["さ","sa","sa"],["し","shi","shi"],["す","su","su"],["せ","se","se"],["そ","so","so"]]},{"t":"Hiragana hàng T","e":"た","w":[["た","ta","ta"],["ち","chi","chi"],["つ","tsu","tsu"],["て","te","te"],["と","to","to"]]},{"t":"Hiragana hàng N","e":"な","w":[["な","na","na"],["に","ni","ni"],["ぬ","nu","nu"],["ね","ne","ne"],["の","no","no"]]}]},{"id":"N5","topics":[{"t":"Chào hỏi","e":"👋","w":[["こんにちは","konnichiwa","xin chào","👋"],["ありがとう","arigatou","cảm ơn","🙏"],["すみません","sumimasen","xin lỗi / xin phép","🙇"],["おはよう","ohayou","chào buổi sáng","🌅"],["さようなら","sayounara","tạm biệt","👋"],["はい","hai","vâng","✅"]]},{"t":"Số đếm","e":"🔢","w":[["いち","ichi","một","1️⃣"],["に","ni","hai","2️⃣"],["さん","san","ba","3️⃣"],["よん","yon","bốn","4️⃣"],["ご","go","năm","5️⃣"],["じゅう","juu","mười","🔟"]]},{"t":"Ăn uống","e":"🍙","w":[["みず","mizu","nước","💧"],["おちゃ","ocha","trà","🍵"],["ごはん","gohan","cơm","🍚"],["たべる","taberu","ăn","😋"],["のむ","nomu","uống","🥤"],["おいしい","oishii","ngon","😍"]]},{"t":"Người","e":"🧑‍🏫","w":[["わたし","watashi","tôi"],["ともだち","tomodachi","bạn bè","🧑‍🤝‍🧑"],["せんせい","sensei","giáo viên","🧑‍🏫"],["おかあさん","okaasan","mẹ (người khác)","👩"],["おとうさん","otousan","bố (người khác)","👨"],["がくせい","gakusei","học sinh","🎒"]]},{"t":"Động vật","e":"🐱","w":[["いぬ","inu","chó","🐶"],["ねこ","neko","mèo","🐱"],["さかな","sakana","cá","🐟"],["とり","tori","chim","🐦"]]}]}];
const ALL=LV.flatMap(l=>l.topics.map(t=>({l:l.id,t:t.t,e:t.e,w:t.w}))),W=ALL.flatMap(g=>g.w.map(w=>w.concat([g.t])));
let P={};try{P=JSON.parse(LS.getItem('PE_LANG')||'{}')}catch(e){}
const key=w=>'ja:'+w[0],save=()=>{try{LS.setItem('PE_LANG',JSON.stringify(P))}catch(e){}};
const say=t=>{if(!window.speechSynthesis)return toast('Trình duyệt chưa hỗ trợ đọc');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='ja-JP';const v=(speechSynthesis.getVoices()||[]).find(x=>/^ja/i.test(x.lang));if(v)u.voice=v;else toast('Máy chưa có giọng tiếng Nhật (Cài đặt → Văn bản sang giọng nói).');u.rate=.8;speechSynthesis.speak(u)};
const RO='a i u e o ka ki ku ke ko sa shi su se so ta chi tsu te to na ni nu ne no ha hi fu he ho ma mi mu me mo ya yu yo ra ri ru re ro wa wo n'.split(' ');
const HI='あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん'.split('');
const KA=HI.map(c=>String.fromCharCode(c.charCodeAt(0)+0x60));
document.head.insertAdjacentHTML('beforeend','<style>.jc{border:1px solid var(--acc-b,#ffe4e6);border-radius:24px;padding:16px;margin:12px 0;background:rgba(255,255,255,.94)}body[data-mode=dark] .jc{background:#1e2040;border-color:#33365f;color:#e5e7eb}.jb{padding:10px 14px;border-radius:14px;background:#fdf2f8;color:#be185d;font-weight:800;font-size:13px;min-height:44px}.jb.on,.jb.pri{background:linear-gradient(135deg,#ec4899,#6366f1);color:#fff}.jg{display:grid;grid-template-columns:repeat(auto-fill,minmax(64px,1fr));gap:8px}.jk{padding:8px 0;border-radius:14px;background:#fdf2f8;text-align:center;font-weight:800;color:#334155}.jk b{display:block;font-size:1.7rem}.jk small{opacity:.6}body[data-mode=dark] .jk{background:#2a2d55;color:#e5e7eb}.jr{display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid #8882}.jr:last-child{border:0}.jr .h{font-size:1.5rem;min-width:4.5rem}.jw{flex:1}.jrow{display:flex;gap:8px;flex-wrap:wrap}.jrow>*{flex:1}.jo{display:block;width:100%;margin:8px 0;text-align:left;padding:12px;border-radius:14px;background:#fdf2f8;font-weight:700;color:#334155}body[data-mode=dark] .jo{background:#2a2d55;color:#e5e7eb}.jo.good{background:#16a34a!important;color:#fff}.jo.bad{background:#dc2626!important;color:#fff}.jm{font-size:12px;opacity:.6}</style>');
let J={v:'home',k:0,f:0,s:'hira'},Q=null;
const sb=t=>`<button class="jb" onclick="JA.say('${esc(t)}')" aria-label="Nghe">🔊</button>`;
const done=()=>W.filter(w=>P[key(w)]).length;
function mk(){return{n:0,sc:0,bad:[],q:shuf(W).slice(0,10).map((w,n)=>{const ty=n%2,f=ty?1:2,seen=new Set([w[f]]),o=[w];for(const x of shuf(W)){if(o.length>=4)break;if(!seen.has(x[f])){seen.add(x[f]);o.push(x)}}return{w,ty,f,o:shuf(o)}})}}
function draw(){const s=$('ja-section');if(!s)return;
 if(J.v==='home'){window.Mimi&&Mimi.drawJa&&Mimi.drawJa();return}
 window.scrollTo(0,0);
 if(J.v==='words')s.innerHTML=`<div class="jc"><b>📚 Từ vựng N5 & kana</b><div class="jm">${done()}/${W.length} đã thuộc</div></div>`+ALL.map(g=>`<div class="jc"><b>${esc(g.e)} ${esc(g.t)}</b> <span class="jm">${esc(g.l)}</span>${g.w.map(w=>`<div class="jr ${P[key(w)]?'jd':''}"><span class="h">${esc(w[0])}</span><div class="jw"><div>${esc(w[1])}</div><div class="jm">${esc(w[2])}</div></div>${sb(w[0])}<button class="jb" onclick="JA.tg('${esc(w[0])}')">${P[key(w)]?'✅':'⬜'}</button></div>`).join('')}</div>`).join('');
 if(J.v==='cards'){const w=W[J.k];s.innerHTML=`<div class="jc" style="text-align:center;min-height:240px;cursor:pointer;display:flex;flex-direction:column;justify-content:center;align-items:center" onclick="JA.flip()"><div class="jm">${J.k+1}/${W.length} · chạm để lật</div><div style="font-size:3.2rem">${esc(w[0])}</div>${J.f?`<div style="font-size:1.3rem">${esc(w[1])}</div><div>${esc(w[2])}</div>`:''}</div><div class="jrow">${sb(w[0])}<button class="jb ${P[key(w)]?'pri':''}" onclick="JA.tg('${esc(w[0])}')">${P[key(w)]?'✅ Đã thuộc':'⬜ Đánh dấu thuộc'}</button></div><div class="jrow" style="margin-top:8px"><button class="jb" onclick="JA.nx(-1)">← Trước</button><button class="jb" onclick="JA.nx(1)">Sau →</button></div>`}
 if(J.v==='kana'){const A=J.s==='kata'?KA:HI;s.innerHTML=`<div class="jc"><div class="jrow"><button class="jb ${J.s==='hira'?'on':''}" onclick="JA.set('hira')">あ Hiragana</button><button class="jb ${J.s==='kata'?'on':''}" onclick="JA.set('kata')">ア Katakana</button></div><p class="jm" style="margin-top:8px">Chạm vào chữ để nghe. Muốn tập viết: bấm “Viết”.</p></div><div class="jc"><div class="jg">${A.map((c,i)=>`<button class="jk" onclick="JA.say('${c}')"><b>${c}</b><small>${RO[i]}</small></button>`).join('')}</div></div><button class="jb pri" style="width:100%" onclick="Write.kana('${J.s}')">✍️ Viết ${J.s==='kata'?'Katakana':'Hiragana'} (xem mẫu từng nét)</button>`}
 if(J.v==='quiz'){if(!Q)Q=mk();
  if(Q.n>=Q.q.length){const p=Q.sc/Q.q.length;if(!Q.d){Q.d=1;if(p>=1)xp('quiz_complete_100');else if(p>=.8)xp('quiz_complete_80')}s.innerHTML=`<div class="jc" style="text-align:center"><div style="font-size:3rem">${p>=.8?'🏆':p>=.5?'👍':'💪'}</div><h3 class="text-xl font-black">${Q.sc}/${Q.q.length} câu đúng</h3>${Q.bad.length?'<p class="jm">Cần ôn lại:</p>'+Q.bad.map(w=>`<div>${esc(w[0])} · ${esc(w[1])} · ${esc(w[2])}</div>`).join(''):'<p>Không sai câu nào!</p>'}<button class="jb pri" style="margin-top:12px" onclick="JA.again()">Làm lại</button></div>`;return}
  const c=Q.q[Q.n],w=c.w;s.innerHTML=`<div class="jc"><div class="jm">Câu ${Q.n+1}/${Q.q.length}</div><div style="text-align:center;margin:12px 0"><div style="font-size:2.6rem">${esc(w[0])}</div>${sb(w[0])}<p class="jm">${c.ty?'Cách đọc đúng?':'Nghĩa là gì?'}</p></div>${c.o.map(x=>`<button class="jo" data-k="${x===w?1:0}">${esc(x[c.f])}</button>`).join('')}<div id="jfb"></div></div>`;
  s.querySelectorAll('.jo').forEach(b=>b.onclick=()=>{const ok=b.dataset.k==='1';s.querySelectorAll('.jo').forEach(x=>{x.disabled=true;if(x.dataset.k==='1')x.classList.add('good')});if(ok){Q.sc++;xp('vocab_correct');try{correctFx()}catch(e){}}else{b.classList.add('bad');Q.bad.push(w);try{wrongFx()}catch(e){}}say(w[0]);$('jfb').innerHTML=`<div class="jm" style="margin-top:8px">${ok?'✅ Chính xác!':'❌ Chưa đúng.'} <b>${esc(w[0])}</b> · ${esc(w[1])} · ${esc(w[2])}</div><button class="jb pri" style="width:100%;margin-top:8px" onclick="JA.next()">Tiếp →</button>`})}}
window.JA={total:W.length,data:()=>({W,ALL}),say,draw,show(v){J.v=v;if(v==='quiz')Q=null;draw()},
 tg(c){const w=W.find(x=>x[0]===c);if(!w)return;P[key(w)]=!P[key(w)];if(P[key(w)])xp('vocab_learned',key(w));save();const y=scrollY;draw();scrollTo(0,y)},
 flip(){J.f=!J.f;draw()},nx(d){J.k=(J.k+d+W.length)%W.length;J.f=0;draw()},set(x){J.s=x;draw()},next(){Q.n++;draw()},again(){Q=mk();draw()}};
})();
