-- ENT303 Study Hub v6 — custom username + 4-digit password
-- Chạy file này 1 lần trong Supabase SQL Editor.
-- Không cần email, không cần mã lớp. Username là tên hiển thị trên leaderboard.
-- Mật khẩu chỉ 4 chữ số; database lưu HASH, không lưu mật khẩu thô.

create extension if not exists pgcrypto;

do $$ begin
  create type public.ent303_xp_kind as enum (
    'vocab_learned','vocab_correct','grammar_correct',
    'quiz_complete_80','quiz_complete_100','quiz_80','quiz_100','lesson_complete'
  );
exception when duplicate_object then null;
end $$;

create table if not exists public.member_accounts (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  username_key text not null unique,
  password_hash text not null,
  notes text not null default '',
  study_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.member_sessions (
  token text primary key,
  user_id uuid not null references public.member_accounts(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days')
);

create table if not exists public.member_xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.member_accounts(id) on delete cascade,
  kind public.ent303_xp_kind not null,
  xp integer not null check (xp > 0 and xp <= 300),
  week_start date not null,
  created_at timestamptz not null default now()
);

create index if not exists member_xp_week_idx on public.member_xp_events(week_start, xp desc);
create index if not exists member_xp_user_idx on public.member_xp_events(user_id, created_at desc);
create index if not exists member_sessions_user_idx on public.member_sessions(user_id);

create or replace function public.ent303_vn_week_start(ts timestamptz default now())
returns date language sql stable as $$
  select date_trunc('week', (ts at time zone 'Asia/Ho_Chi_Minh'))::date;
$$;

create or replace function public.ent303_make_session(p_user_id uuid)
returns text language plpgsql security definer set search_path = public as $$
declare t text := encode(gen_random_bytes(32),'hex');
begin
  insert into public.member_sessions(token,user_id) values(t,p_user_id);
  return t;
end;
$$;

create or replace function public.ent303_register(p_username text, p_password text)
returns table(session_token text, user_id uuid, username text)
language plpgsql security definer set search_path = public as $$
declare
  u text := trim(p_username);
  uk text := lower(trim(p_username));
  uid uuid;
  tok text;
begin
  if length(u) < 2 or length(u) > 30 then
    raise exception 'Tên đăng nhập phải từ 2 đến 30 ký tự.';
  end if;
  if u ~ '[[:cntrl:]]' then
    raise exception 'Tên có ký tự không hợp lệ.';
  end if;
  if p_password !~ '^[0-9]{4}$' then
    raise exception 'Mật khẩu phải đúng 4 chữ số.';
  end if;
  if exists(select 1 from public.member_accounts where username_key=uk) then
    raise exception 'Tên này đã có người dùng. Chọn tên khác nha.';
  end if;
  insert into public.member_accounts(username,username_key,password_hash)
  values(u,uk,crypt(p_password,gen_salt('bf')))
  returning id into uid;
  tok := public.ent303_make_session(uid);
  return query select tok,uid,u;
end;
$$;

create or replace function public.ent303_login(p_username text, p_password text)
returns table(session_token text, user_id uuid, username text)
language plpgsql security definer set search_path = public as $$
declare
  row public.member_accounts;
  tok text;
begin
  select * into row from public.member_accounts where username_key=lower(trim(p_username));
  if row.id is null or row.password_hash <> crypt(p_password,row.password_hash) then
    raise exception 'Tên đăng nhập hoặc mật khẩu chưa đúng.';
  end if;
  delete from public.member_sessions where user_id=row.id and expires_at < now();
  tok := public.ent303_make_session(row.id);
  return query select tok,row.id,row.username;
end;
$$;

create or replace function public.ent303_me(p_token text)
returns table(user_id uuid, username text, notes text, study_state jsonb)
language plpgsql security definer set search_path = public as $$
declare uid uuid;
begin
  select s.user_id into uid from public.member_sessions s where s.token=p_token and s.expires_at>now();
  if uid is null then raise exception 'SESSION_EXPIRED'; end if;
  update public.member_sessions set expires_at=now()+interval '30 days' where token=p_token;
  return query select a.id,a.username,a.notes,a.study_state from public.member_accounts a where a.id=uid;
end;
$$;


create or replace function public.ent303_save_state(p_token text, p_state jsonb)
returns boolean language plpgsql security definer set search_path = public as $$
declare uid uuid;
begin
  select user_id into uid from public.member_sessions where token=p_token and expires_at>now();
  if uid is null then raise exception 'SESSION_EXPIRED'; end if;
  update public.member_accounts set study_state=coalesce(p_state,'{}'::jsonb),updated_at=now() where id=uid;
  return true;
end;
$$;

create or replace function public.ent303_logout(p_token text)
returns void language sql security definer set search_path = public as $$
  delete from public.member_sessions where token=p_token;
$$;

create or replace function public.ent303_save_notes(p_token text, p_notes text)
returns boolean language plpgsql security definer set search_path = public as $$
declare uid uuid;
begin
  select user_id into uid from public.member_sessions where token=p_token and expires_at>now();
  if uid is null then raise exception 'SESSION_EXPIRED'; end if;
  update public.member_accounts set notes=coalesce(p_notes,''),updated_at=now() where id=uid;
  return true;
end;
$$;

create or replace function public.ent303_xp_for_kind(p_kind public.ent303_xp_kind)
returns integer language sql immutable as $$
  select case p_kind
    when 'vocab_learned' then 2
    when 'vocab_correct' then 3
    when 'grammar_correct' then 3
    when 'quiz_complete_80' then 25
    when 'quiz_complete_100' then 50
    when 'quiz_80' then 25
    when 'quiz_100' then 50
    when 'lesson_complete' then 20
  end;
$$;

create or replace function public.ent303_record_xp(p_token text, p_kind public.ent303_xp_kind)
returns integer language plpgsql security definer set search_path = public as $$
declare
  uid uuid;
  pts integer;
  used_today integer;
  allowed integer;
  inserted_pts integer;
  vn_today_start timestamptz := date_trunc('day', now() at time zone 'Asia/Ho_Chi_Minh') at time zone 'Asia/Ho_Chi_Minh';
begin
  select user_id into uid from public.member_sessions where token=p_token and expires_at>now();
  if uid is null then raise exception 'SESSION_EXPIRED'; end if;
  pts := public.ent303_xp_for_kind(p_kind);
  select coalesce(sum(xp),0) into used_today from public.member_xp_events
  where user_id=uid and created_at>=vn_today_start and created_at<vn_today_start+interval '1 day';
  allowed := greatest(0,300-used_today);
  inserted_pts := least(pts,allowed);
  if inserted_pts<=0 then return 0; end if;
  insert into public.member_xp_events(user_id,kind,xp,week_start)
  values(uid,p_kind,inserted_pts,public.ent303_vn_week_start(now()));
  return inserted_pts;
end;
$$;

create or replace function public.ent303_leaderboard(p_token text)
returns table(user_id uuid, username text, weekly_xp bigint)
language plpgsql security definer set search_path = public as $$
declare ok boolean;
begin
  select exists(select 1 from public.member_sessions where token=p_token and expires_at>now()) into ok;
  if not ok then raise exception 'SESSION_EXPIRED'; end if;
  return query
  select a.id,a.username,coalesce(sum(e.xp),0)::bigint
  from public.member_accounts a
  join public.member_xp_events e on e.user_id=a.id and e.week_start=public.ent303_vn_week_start(now())
  group by a.id,a.username
  order by weekly_xp desc, lower(a.username) asc
  limit 100;
end;
$$;

create or replace function public.ent303_previous_winner(p_token text)
returns table(user_id uuid, username text, weekly_xp bigint)
language plpgsql security definer set search_path = public as $$
declare ok boolean;
begin
  select exists(select 1 from public.member_sessions where token=p_token and expires_at>now()) into ok;
  if not ok then raise exception 'SESSION_EXPIRED'; end if;
  return query
  select a.id,a.username,coalesce(sum(e.xp),0)::bigint
  from public.member_accounts a
  join public.member_xp_events e on e.user_id=a.id and e.week_start=public.ent303_vn_week_start(now())-7
  group by a.id,a.username
  order by weekly_xp desc, lower(a.username) asc
  limit 1;
end;
$$;

revoke all on table public.member_accounts from anon, authenticated;
revoke all on table public.member_sessions from anon, authenticated;
revoke all on table public.member_xp_events from anon, authenticated;
revoke all on function public.ent303_register(text,text) from public;
revoke all on function public.ent303_login(text,text) from public;
revoke all on function public.ent303_me(text) from public;
revoke all on function public.ent303_save_state(text,jsonb) from public;
revoke all on function public.ent303_logout(text) from public;
revoke all on function public.ent303_save_notes(text,text) from public;
revoke all on function public.ent303_record_xp(text,public.ent303_xp_kind) from public;
revoke all on function public.ent303_leaderboard(text) from public;
revoke all on function public.ent303_previous_winner(text) from public;
grant execute on function public.ent303_register(text,text) to anon, authenticated;
grant execute on function public.ent303_login(text,text) to anon, authenticated;
grant execute on function public.ent303_me(text) to anon, authenticated;
grant execute on function public.ent303_save_state(text,jsonb) to anon, authenticated;
grant execute on function public.ent303_logout(text) to anon, authenticated;
grant execute on function public.ent303_save_notes(text,text) to anon, authenticated;
grant execute on function public.ent303_record_xp(text,public.ent303_xp_kind) to anon, authenticated;
grant execute on function public.ent303_leaderboard(text) to anon, authenticated;
grant execute on function public.ent303_previous_winner(text) to anon, authenticated;
