-- Chạy 1 lần trong Supabase → SQL Editor (sau supabase-schema.sql)
-- Host = tài khoản có tên đăng nhập "phamthithanhtam". Quyền host được kiểm tra Ở SERVER (RLS), không phải ở trình duyệt.
-- QUAN TRỌNG: hãy đăng ký tài khoản host TRƯỚC khi gửi link cho người khác.
create or replace function public.is_host() returns boolean language sql stable as $$
  select coalesce(auth.jwt()->>'email','') = '5ef93c022cd91f147089fada01da85fc@ent303.app' $$;

create table if not exists public.host_content (id int primary key default 1 check (id=1), data jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.host_content_history (id bigint generated by default as identity primary key, data jsonb not null, saved_at timestamptz not null default now());
create table if not exists public.announcements (id bigint generated by default as identity primary key, text text not null, created_at timestamptz not null default now());

create or replace function public.keep_host_history() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into host_content_history(data) values (old.data);
  delete from host_content_history where id not in (select id from host_content_history order by id desc limit 20);
  return new; end $$;
drop trigger if exists trg_host_hist on public.host_content;
create trigger trg_host_hist before update on public.host_content for each row execute function public.keep_host_history();

alter table public.host_content enable row level security;
alter table public.host_content_history enable row level security;
alter table public.announcements enable row level security;
drop policy if exists hc_sel on public.host_content; create policy hc_sel on public.host_content for select to anon, authenticated using (true);
drop policy if exists hc_ins on public.host_content; create policy hc_ins on public.host_content for insert to authenticated with check (public.is_host());
drop policy if exists hc_upd on public.host_content; create policy hc_upd on public.host_content for update to authenticated using (public.is_host()) with check (public.is_host());
drop policy if exists hh_sel on public.host_content_history; create policy hh_sel on public.host_content_history for select to authenticated using (public.is_host());
drop policy if exists an_sel on public.announcements; create policy an_sel on public.announcements for select to anon, authenticated using (true);
drop policy if exists an_ins on public.announcements; create policy an_ins on public.announcements for insert to authenticated with check (public.is_host());
drop policy if exists an_del on public.announcements; create policy an_del on public.announcements for delete to authenticated using (public.is_host());
