-- =========================================================
-- PRACTICE ENGLISH / ENT303 STUDY HUB — SUPABASE SCHEMA V7
-- Chạy toàn bộ file này trong Supabase SQL Editor.
-- Có thể chạy lại; dùng IF NOT EXISTS / CREATE OR REPLACE.
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Bạn học',
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists data jsonb not null default '{}'::jsonb;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();
alter table public.profiles enable row level security;

drop policy if exists p_sel on public.profiles;
create policy p_sel on public.profiles for select to authenticated using (auth.uid() = id);
drop policy if exists p_ins on public.profiles;
create policy p_ins on public.profiles for insert to authenticated with check (auth.uid() = id);
drop policy if exists p_upd on public.profiles;
create policy p_upd on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create table if not exists public.study_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  xp integer not null,
  created_at timestamptz not null default now()
);
alter table public.study_events enable row level security;
drop policy if exists study_events_insert on public.study_events;
create policy study_events_insert on public.study_events for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists study_events_select on public.study_events;
create policy study_events_select on public.study_events for select to authenticated using (auth.uid() = user_id);

create or replace function public.record_study_event(p_kind text)
returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); pts int; today_xp int;
begin
  if uid is null then raise exception 'not_authenticated'; end if;
  pts:=case p_kind
    when 'vocab_learned' then 2
    when 'vocab_correct' then 2
    when 'grammar_correct' then 3
    when 'quiz_complete_80' then 25
    when 'quiz_complete_100' then 50
    else 0 end;
  if pts<=0 then raise exception 'invalid_event'; end if;
  select coalesce(sum(xp),0) into today_xp
  from public.study_events
  where user_id=uid
    and created_at >= (date_trunc('day',now() at time zone 'Asia/Ho_Chi_Minh') at time zone 'Asia/Ho_Chi_Minh');
  if today_xp>=300 then return json_build_object('ok',false,'reason','daily_limit'); end if;
  insert into public.study_events(user_id,kind,xp) values(uid,p_kind,least(pts,300-today_xp));
  return json_build_object('ok',true);
end $$;
grant execute on function public.record_study_event(text) to authenticated;

create or replace function public.get_weekly_leaderboard()
returns table(user_id uuid, display_name text, weekly_xp bigint)
language sql security definer set search_path=public as $$
  select p.id,p.display_name,coalesce(sum(e.xp),0)::bigint
  from public.profiles p
  left join public.study_events e on e.user_id=p.id
    and e.created_at >= (date_trunc('week',now() at time zone 'Asia/Ho_Chi_Minh') at time zone 'Asia/Ho_Chi_Minh')
  group by p.id,p.display_name
  order by 3 desc,2 asc limit 30
$$;
grant execute on function public.get_weekly_leaderboard() to authenticated;

create table if not exists public.app_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('host','student')) default 'student',
  created_at timestamptz not null default now()
);
alter table public.app_roles enable row level security;
drop policy if exists app_roles_self on public.app_roles;
create policy app_roles_self on public.app_roles for select to authenticated using (auth.uid() = user_id);

create or replace function public.is_host()
returns boolean language sql security definer set search_path=public as $$
  select exists(select 1 from public.app_roles where user_id=auth.uid() and role='host');
$$;
grant execute on function public.is_host() to anon, authenticated;

-- Host account bootstrap.
-- The app uses the username as a deterministic Supabase email internally.
-- The real Supabase password is still protected by Auth; this RPC only grants
-- the host role after the user has already authenticated with the host credentials.
create or replace function public.claim_host_account(p_username text, p_pin text)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not_authenticated'; end if;

  if lower(trim(p_username)) <> 'phamthithanhtam' or p_pin <> '2007' then
    return false;
  end if;

  if lower(coalesce(auth.email(),'')) <> '5ef93c022cd91f147089fada01da85fc@ent303.app' then
    return false;
  end if;

  insert into public.app_roles(user_id,role)
  values(uid,'host')
  on conflict(user_id) do update set role='host';

  insert into public.profiles(id,display_name)
  values(uid,'phamthithanhtam')
  on conflict(id) do update set display_name='phamthithanhtam',updated_at=now();

  return true;
end
$$;
grant execute on function public.claim_host_account(text,text) to authenticated;

create table if not exists public.shared_announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  published boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.shared_announcements enable row level security;
drop policy if exists announcements_public_read on public.shared_announcements;
create policy announcements_public_read on public.shared_announcements for select to anon,authenticated using (published=true or public.is_host());
drop policy if exists announcements_host_write on public.shared_announcements;
create policy announcements_host_write on public.shared_announcements for all to authenticated using (public.is_host()) with check (public.is_host());

create table if not exists public.shared_vocab (
  id bigint generated by default as identity primary key,
  unit_id integer not null check (unit_id between 1 and 10),
  payload jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id) on delete cascade,
  published boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.shared_vocab enable row level security;
drop policy if exists shared_vocab_public_read on public.shared_vocab;
create policy shared_vocab_public_read on public.shared_vocab for select to anon,authenticated using (published=true or public.is_host());
drop policy if exists shared_vocab_host_write on public.shared_vocab;
create policy shared_vocab_host_write on public.shared_vocab for all to authenticated using (public.is_host()) with check (public.is_host());

create table if not exists public.community_questions (
  id bigint generated by default as identity primary key,
  unit_id integer not null check (unit_id between 1 and 10),
  payload jsonb not null default '{}'::jsonb,
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.community_questions enable row level security;
drop policy if exists community_public_read on public.community_questions;
create policy community_public_read on public.community_questions for select to authenticated using (status='approved' or created_by=auth.uid() or public.is_host());
drop policy if exists community_student_insert on public.community_questions;
create policy community_student_insert on public.community_questions for insert to authenticated with check (auth.uid()=created_by);
drop policy if exists community_host_update on public.community_questions;
create policy community_host_update on public.community_questions for update to authenticated using (public.is_host()) with check (public.is_host());
drop policy if exists community_host_delete on public.community_questions;
create policy community_host_delete on public.community_questions for delete to authenticated using (public.is_host());

-- Auto-create a private profile whenever a Supabase user is created.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,display_name)
  values(new.id,coalesce(new.raw_user_meta_data->>'display_name','Bạn học'))
  on conflict(id) do nothing;
  return new;
end
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();



-- =========================================================
-- V8 GLOBAL CONTENT OVERRIDES
-- Host chỉnh sửa từ có sẵn -> tất cả tài khoản nhận bản mới
-- =========================================================

create table if not exists public.content_overrides (
  id bigint generated by default as identity primary key,
  unit_id integer not null check (unit_id between 1 and 10),
  word_key text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_by uuid not null references auth.users(id) on delete cascade,
  updated_at timestamptz not null default now(),
  unique(unit_id, word_key)
);

alter table public.content_overrides enable row level security;

drop policy if exists content_overrides_read on public.content_overrides;
create policy content_overrides_read
on public.content_overrides
for select
to anon, authenticated
using (true);

drop policy if exists content_overrides_host_write on public.content_overrides;
create policy content_overrides_host_write
on public.content_overrides
for all
to authenticated
using (public.is_host())
with check (public.is_host());

-- =========================================================
-- V8 HOST CLAIM
-- Username: phamthithanhtam
-- PIN is stored as MD5, not plaintext in the public schema.
-- =========================================================

create or replace function public.claim_host_account(
  p_username text,
  p_pin text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  nm text := lower(trim(p_username));
begin
  if uid is null then return false; end if;

  if nm <> 'phamthithanhtam' then return false; end if;
  if md5(coalesce(p_pin,'')) <> 'a00e5eb0973d24649a4a920fc53d9564' then return false; end if;

  if lower(coalesce((select raw_user_meta_data->>'display_name' from auth.users where id=uid),'')) <> nm then
    return false;
  end if;

  insert into public.app_roles(user_id, role)
  values(uid,'host')
  on conflict(user_id) do update set role='host';

  return true;
end;
$$;

grant execute on function public.claim_host_account(text,text) to authenticated;

